version: '3'
services:
  connector-template:
    image: opencti/connector-template:5.1.3
    environment:
      - OPENCTI_URL=https://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=Maxmind
      - CONNECTOR_SCOPE= # MIME type or Stix Object
      - CONNECTOR_CONFIDENCE_LEVEL=20 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
